---
Name: ElasticSearch
---
Firesphere\ElasticSearch\Services\ElasticCoreService:
  config:
    endpoint:
      - host: https://es01
        port: 3002
        enterprise-search:
          username: 'elastic'
          password: 'changeme'
  cpucores: 4
Firesphere\ElasticSearch\Indexes\BaseIndex:
  ConsumerHealth:
    Classes:
      - Page
    FulltextFields:
      - Title
      - getElementsForSearch
    FilterFields: []
    FacetFields: []
#      Firesphere\StickerTrade\Models\Tag:
#        BaseClass: Firesphere\StickerTrade\Models\Sticker
#        Field: Tags.ID
#        Title: Tag
