name: 'PHPUnit tests'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: ddev/github-action-setup-ddev@v1
      - run: git clone https://github.com/Firesphere/search-testapp.git app
      - run: ddev composer install --prefer-dist --no-interaction --no-progress
      - run: ddev composer vendor-expose
      - run: cp example.env .env
      - run: ddev sake dev/build
      - run: ddev xdebug
      - run: ddev exec phpunit tests --coverage-clover ./coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CORE_CODECOV_TOKEN }}
