name: 'PHPUnit tests'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    timeout_minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: ddev/github-action-setup-ddev@v1
      # example: composer install
      - run: ddev composer install --prefer-dist --no-interaction --no-progress
      - run: ddev composer vendor-expose
      - run: cp .github/assets/search.yml.test app/_config/search.yml
      - run: cp .github/assets/SearchIndex.php.test app/src/SearchIndex.php
      - run: cp example.env .env
      - run: ddev sake dev/build
      - run: ddev xdebug
      - run: ddev exec phpunit tests --coverage-clover ./coverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
